FROM python:3.13-alpine

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    UV_NO_PROGRESS=1

WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

RUN apk add --no-cache ffmpeg deno tzdata

COPY pyproject.toml uv.lock* ./

RUN uv sync --frozen --no-install-project

EXPOSE 5000
CMD ["uv", "run", "flask", "run", "--host=0.0.0.0", "--port=5000", "--reload"]
